version: "3.0"

networks:
  ghost_network:


services:

  database:
    image: mysql:8
    restart: always
    container_name: database_container
    volumes:
      - ./mysql/config:/etc/mysql/conf.d/
      - ./mysql/database:/var/lib/mysql/
      - ./mysql/entrypoints:/docker-entrypoint-initdb.d/
      - ./mysql/home:/home/
    environment:
      MYSQL_USER: ghost
      MYSQL_DATABASE: ghost
      MYSQL_PASSWORD: glyz205070410
      MYSQL_ROOT_PASSWORD: glyz205070410
    networks:
      - ghost_network

  ghost:
    image: ghost:4
    restart: always
    container_name: ghost_container
    ports:
      - 2368:2368
    volumes:
      - ./ghost/blog:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__user: ghost
      database__connection__host: database
      database__connection__database: ghost
      database__connection__password: glyz205070410
    networks:
      - ghost_network
